server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass http://auth-service:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/posts {
        proxy_pass http://post-service:8002/posts;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/comments {
        proxy_pass http://comment-service:8003/comments;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
